platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/golang-release

inputs:
- name: input_repo
- name: golang-release

outputs:
- name: output_repo

run:
  path: golang-release/ci/tasks/shared/bump-golang-package.sh

params:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: bots@cloudfoundry.org
  PACKAGES:
  PACKAGES_TO_REMOVE: []
  PRIVATE_YML:
  RELEASE_DIR:
