#!/bin/bash

# Update these variables when adding a new line
old=1.13
last=1.14
new=1.15

# src
cp -fr src/${last}/ src/${new}/
find src/${new} -type file -print0 | xargs -0 sed -i "" "s/${last}/${new}/g"
rm -fr src/${old}

# packages
for dir in darwin darwin-test linux linux-test windows windows-test; do
    cp -fr packages/golang-{${last},${new}}-${dir}/
    rm -fr packages/golang-${old}-${dir}/
done

find packages/*-${new}-* -type file -print0 | xargs -0 sed -i "" "s/${last}/${new}/g"
find packages/*-1-* -type file -print0 | xargs -0 sed -i "" "s/${last}/${new}/g"

# jobs
for dir in test test-windows; do
    cp -fr jobs/golang-{${last},${new}}-${dir}/
done

find jobs/*-${new}-* -type file -print0 | xargs -0 sed -i "" "s/${last}/${new}/g"
find jobs/*-1-* -type file -print0 | xargs -0 sed -i "" "s/${last}/${new}/g"

# blobs
for blob in $(bosh blobs | awk '{print $1}' | grep go${old}); do
    bosh remove-blob ${blob}
done

# ci
find ci -type file -print0 | xargs -0 sed -i "" "s/${old}/${new}/g"

echo "added ${new}, removed ${old}"
echo "please commit changes and push"
echo "when pushed run `./ci/configure.sh` to update pipeline"
echo "the pipeline will add the required blobs"
