#!/usr/bin/env bash

set -eu

for tool in git curl jq; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "required tool '${tool}' not found in task image" >&2
    exit 1
  fi
done

cd golang-release

current_new="$(grep -oE '^new=[0-9]+\.[0-9]+' ci/tasks/add-line.sh | cut -d= -f2)"
current_last="$(grep -oE '^last=[0-9]+\.[0-9]+' ci/tasks/add-line.sh | cut -d= -f2)"

detected_new="$(
  curl -sf 'https://go.dev/dl/?mode=json' \
    | jq -r '.[] | select(.stable == true) | .version[2:] | capture("^(?<line>[0-9]+\\.[0-9]+)").line' \
    | sort -V \
    | uniq \
    | tail -n1
)"

if [ -z "${detected_new}" ]; then
  echo "could not determine the latest stable golang line from go.dev, skipping" >&2
  exit 0
fi

if [ "$(printf '%s\n%s\n' "${current_new}" "${detected_new}" | sort -V | tail -n1)" != "${detected_new}" ] \
  || [ "${detected_new}" = "${current_new}" ]; then
  echo "no new golang line found (tracking up to ${current_new}, latest available is ${detected_new})"
  exit 0
fi

echo "found new golang line ${detected_new}, proposing ci/tasks/add-line.sh update (${current_last} -> ${current_new} -> ${detected_new})"

git config user.name "${GIT_USER_NAME}"
git config user.email "${GIT_USER_EMAIL}"

# The golang-release input is checked out over SSH by the git resource, but this
# task only holds GH_TOKEN, so reads go over anonymous HTTPS and the push
# carries the token in its URL. Never echo push_url.
repo="cloudfoundry/bosh-package-golang-release"
git remote set-url origin "https://github.com/${repo}.git"
push_url="https://x-access-token:${GH_TOKEN}@github.com/${repo}.git"

branch="add-go-${detected_new}-line"

if git ls-remote --exit-code origin "refs/heads/${branch}" >/dev/null 2>&1; then
  echo "branch ${branch} already exists on origin, presumably awaiting PR review; skipping until it is merged or closed"
  exit 0
fi

git checkout -b "${branch}"

sed -i "s/^old=.*/old=${current_last}/" ci/tasks/add-line.sh
sed -i "s/^last=.*/last=${current_new}/" ci/tasks/add-line.sh
sed -i "s/^new=.*/new=${detected_new}/" ci/tasks/add-line.sh

./ci/tasks/add-line.sh

git add -A
git commit -m "Add golang ${detected_new} line" -m "Drops golang ${current_last}, adds golang ${detected_new}. Generated by the propose-new-golang-line CI job from ci/tasks/add-line.sh."

git push "${push_url}" "refs/heads/${branch}"

body="Automatically generated by the \`propose-new-golang-line\` CI job by running \`ci/tasks/add-line.sh\` (${current_last} -> dropped, ${current_new} -> retained, ${detected_new} -> added).

Please review before merging, in particular:
- \`ci/pipeline.yml\`: \`ci/tasks/add-line.sh\` blindly text-substitutes version numbers across \`ci/\`, which can move the \"archived\" / \`include=all\` \`dynamic-metalink\` resource logic onto the wrong line. Confirm that comment/logic is attached to whichever of the two retained lines (${current_new}, ${detected_new}) is actually the older/archived one, not just wherever the substitution happened to leave it.
- The \`bump\` job's blobs for the new line will not exist until this PR merges; \`build-docker-image\` will fail in the meantime, matching the existing manual-process note in README.md."

payload="$(
  jq -n \
    --arg title "Add golang ${detected_new} line" \
    --arg head "${branch}" \
    --arg body "${body}" \
    '{title: $title, head: $head, base: "main", body: $body}'
)"

if ! response="$(
  curl -s --fail-with-body -X POST \
    -H "Authorization: Bearer ${GH_TOKEN}" \
    -H 'Accept: application/vnd.github+json' \
    -H 'X-GitHub-Api-Version: 2022-11-28' \
    --data-binary "${payload}" \
    "https://api.github.com/repos/${repo}/pulls"
)"; then
  echo "failed to open pull request: ${response}" >&2
  exit 1
fi

echo "opened $(printf '%s' "${response}" | jq -r '.html_url')"
