---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh/warden-cpi

inputs:
- name: golang-release
- name: stemcell

run:
  path: golang-release/ci/tasks/test.sh

params:
  PRIVATE_YML: replace-me
