#!/bin/bash

set -eux

echo "Testing compile compability"
/var/vcap/packages/golang-1.19-linux-test/bin/test

echo "Testing runtime compability"
source /var/vcap/packages/golang-1.19-linux/bosh/runtime.env
go run /var/vcap/packages/golang-1.19-linux-test/test.go
